title = "kottesh"
description = "ratata"
base_url = "https://kottesh.xyz"

compile_sass = false 
build_search_index = true

generate_feeds = false 
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "tags", feed = true}
]

generate_robots_txt = true


[markdown]
highlight_code = false 
render_emoji = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false 
smart_punctuation = true 
lazy_async_image = false
bottom_footnotes = true 

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[extra]
routes = [
    {name = "home", path = "/"},
    {name = "posts", path = "/posts/"},
    {name = "about", path = "/about/"},
    {name = "resume", path = "/resume.pdf"}
] 

socials = [
    {title = "github", link = "https://github.com/kottesh"},
    {title = "linkedin", link = "https://linkedin.com/in/kottesh"},
    {title = "x", link = "https://x.com/shreekottes"},
    {title = "say hi@kottesh.xyz", link = "mailto:hi@kottesh.xyz"},
]
