title = "kottesh.xyz"
description = "Bloop Bleep Bip"
base_url = "https://kottesh.xyz"

compile_sass = false 
build_search_index = true

generate_feeds = false 
feed_filenames = ["atom.xml"]

generate_robots_txt = true


[markdown]
highlight_code = false 
render_emoji = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false
lazy_async_image = false
bottom_footnotes = true 

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[extra]

routes = [
    {name="home", path="/"},
    {name="blog", path="/blog/"},
    {name="about", path="/about/"},
    {name="pow", path="/pow/"}
] 

socials = [
    {title="github", link="https://github.com/kottesh", icon="/icons/github.svg"},
    {title="linkedin", link="https://linkedin.com/in/kottesh", icon="/icons/linkedin.svg"},
    {title="x", link="https://x.com/shreekottes", icon="/icons/x.svg"},
    {title="say hi@kottesh.xyz", link="mailto:hi@kottesh.xyz", icon="/icons/envelope.svg"},
]
