name: deploy to cloudflare pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: install latest zola from source
        run: |
          RELEASE=$(curl -s https://api.github.com/repos/getzola/zola/releases/latest | grep tag_name | cut -d '"' -f 4)
          ZOLA="https://github.com/getzola/zola/releases/download/$RELEASE/zola-$RELEASE-x86_64-unknown-linux-gnu.tar.gz"
          curl -sL $ZOLA | sudo tar -xz -C /usr/local/bin

      - name: build kottesh.xyz
        run: |
          npm install
          npm run build

      #- name: build site
      #  run: zola build
      #
      #- name: build tailwindcss
      #  run: npm i tailwindcss@3 @tailwindcss/typography && npx tailwindcss -i ./styles/main.css -o ./public/style.css --minify
      
      - name: publish to cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACC_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: kottesh 
          directory: public

