name: deploy to cloudflare pages

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: install latest zola from source
        run: |
          RELEASE=$(curl -s https://api.github.com/repos/getzola/zola/releases/latest | grep tag_name | cut -d '"' -f 4)
          ZOLA="https://github.com/getzola/zola/releases/download/$RELEASE/zola-$RELEASE-x86_64-unknown-linux-gnu.tar.gz"
          curl -sL $ZOLA | sudo tar -xz -C /usr/local/bin

      - name: build site
        run: zola build

      - name: build tailwindcss
        run: npx tailwindcss -i ./styles/main.css -o ./public/style.css --minify
      
      - name: publish to cloudflare
        uses: cloudflare/pages-actions@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACC_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: sk 
          directory: public

